name: cutout_text_effect
description: Make cutout effect of your text in an easy way.
version: 0.0.1
author: Lokesh Jangid <lkrjangid@gmail.com>
homepage: https://github.com/lkrjangid1/cutout_text_effect
repository: https://github.com/lkrjangid1/cutout_text_effect

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

